import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[shell]
program = "/usr/bin/tmux"
args = ["new-session"]


[font]
    normal = { family = "GohuFont14NerdFont", style = "Regular" }
    bold = { family = "GohuFont14NerdFont", style = "Bold" }
    italic = { family = "GohuFont14NerdFont", style = "Italic" }
    size = 12.0
    offset = { x = 0, y = 0 }
    glyph_offset = { x = 0, y = 0 }
